# Generated by Django 6.0.7 on 2026-07-18 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=100)),
                ('duration_ms', models.FloatField()),
                ('queries_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'метрика',
                'verbose_name_plural': 'метрики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('venue', models.CharField(max_length=200, verbose_name='площадка')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена билета')),
                ('total_tickets', models.PositiveIntegerField(verbose_name='всего билетов')),
                ('available_tickets', models.PositiveIntegerField(verbose_name='доступно билетов')),
                ('is_on_sale', models.BooleanField(default=True, verbose_name='продажа открыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'концерт',
                'verbose_name_plural': 'концерты',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['is_on_sale', 'starts_at'], name='highloadapp_is_on_s_624f38_idx'), models.Index(fields=['available_tickets'], name='highloadapp_availab_ef5bda_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='email покупателя')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], db_index=True, default='confirmed', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='создан')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='highloadapps.concert', verbose_name='концерт')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['concert', 'status'], name='highloadapp_concert_f17995_idx'), models.Index(fields=['buyer_email', 'created_at'], name='highloadapp_buyer_e_7bc66f_idx')],
            },
        ),
    ]
